[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
twitter_dapp = "FbzSKvffw1VKoqyTPJjZxQrd2mkXS43P96t3vKNhezEU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/zebra/.config/solana/id.json" 

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
